name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------- Checkout ----------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------- Node ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # ---------- Backend ----------
      - name: Install Backend
        run: |
          cd transport-backend
          npm install

      - name: Backend sanity check
        run: |
          cd transport-backend
          node -e "console.log('Backend OK')"

      # ---------- Frontend ----------
      - name: Install Frontend
        run: |
          cd transport-frontend
          npm install

      - name: Build Frontend
        run: |
          cd transport-frontend
          npm run build

      # ---------- Python ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ML Dependencies
        run: |
          cd ml-services
          pip install -r requirements.txt

      - name: ML sanity check
        run: |
          cd ml-services
          python -c "print('ML OK')"
    # ---------- Start ML Service ----------
      - name: Start Flask Server
        run: |
          cd ml-services
          nohup python app.py &
          sleep 5

      # ---------- Test ML API ----------
      - name: Test Prediction API
        run: |
          curl -X POST http://127.0.0.1:9000/predict \
          -H "Content-Type: application/json" \
          -d '{"route_name":"101","time_slot":"8AM","day":"Monday","weather":"clear"}'